# https://docs.astral.sh/ruff/rules/
line-length = 120
target-version = "py313"
exclude = [".ruff_cache", "**/.pytest_cache", "**/.venv", "dumpyard"]
[lint]
select = ["ALL"]
ignore = ["N", "BLE", "COM", "D", "G004", "ERA001", "T201", "TRY002", "TD", "FIX", "S101", "PLR0913", "PLR2004"]
# N = pep8-naming
# BLE = flake8-blind-except
# COM = flake8-commas
# D = Documentation
# G004 = logging-f-string
# ERA001 = commented-out-code
# T201 = Allow print statements
# TRY002 = Allow raise Exception (without subclassing it)
# TD = TODO
# FIX
# S101 = use of assert
# PLR0913 = Too many arguments in function definition
# PLR2004 = Magic value used in comparison, consider replacing ... with a constant variable
