# https://docs.astral.sh/ruff/rules/
line-length = 120
target-version = "py313"
exclude = [".ruff_cache", "**/.pytest_cache", "**/.venv", "dumpyard"]
[lint]
select = ["ALL"]
ignore = ["N", "BLE", "COM", "D101", "D102", "D104", "D107", "D203", "D212", "G004", "ERA001", "T201", "TRY002", "TD", "FIX", "S101", "PLR0913", "PLR2004"]
# N = pep8-naming
# BLE = flake8-blind-except
# COM = flake8-commas
# D101 = Missing docstring in public class
# D102 = Missing docstring in public method
# D104 = Missing docstring in public package
# D107 = Missing docstring in `__init__`
# D203 = incorrect-blank-line-before-class  (conflicts with `no-blank-line-before-class` (D211))
# D212 = multi-line-summary-first-line  (conflicts with `multi-line-summary-second-line` (D213))
# G004 = logging-f-string
# ERA001 = commented-out-code
# T201 = Allow print statements
# TRY002 = Allow raise Exception (without subclassing it)
# TD = TODO
# FIX
# S101 = use of assert
# PLR0913 = Too many arguments in function definition
# PLR2004 = Magic value used in comparison, consider replacing ... with a constant variable
